@startuml
left to right direction
actor User

User --> (Авторизоваться)
User --> (Создать документ)
User --> (Посмотреть список документов)
User --> (Отсортировать список документов)
User --> (Найти документы по части имени)
@enduml
